config:
  grafana:
    url: localhost:3000
    user: admin
    password: admin
  ldap:
    useNTML: True
    url: ldap.forumsys.com
    searchBase: dc=example,dc=com
    groupDescriptor: ou
    groupSearchFilter: ()
    memberAttributeName: uniqueMember
    userLoginAttribute: uid
    login: cn=read-only-admin,dc=example,dc=com
    password: password
  csvPath: test.csv

